### ISSUE TITLE
"rsync" could not be found on your PATH.

### ISSUE THREAD

**Issue by dinbtechit** [skecskes/vagrant-centos7-ansible-lamp#1]
C:\Users\SrinivD1\Desktop\vagrantvms\vagrant-centos7-ansible-lamp [master +0 ~1 -0]> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'centos/7' is up to date...
==> default: Fixed port collision for 443 => 443. Now on port 2201.
==> default: Fixed port collision for 22 => 2222. Now on port 2202.
**"rsync" could not be found on your PATH. Make sure that rsync
is properly installed on your system and available on the PATH.**

**Comment by skecskes** [comment]
Rsync used by vagrant is normally available on unix systems. I see you have Windows as your main operating system. You need to have rsync.exe and set its location in your PATH variable. On Windows, rsync installed with Cygwin or MinGW will be detected by Vagrant and works well. 

Anyway, this is not bug, but rather a requirement.
