### ISSUE TITLE
No ansible on vagrant box... can't provision

### ISSUE THREAD

**Issue by TimOgilvy** [skecskes/vagrant-centos7-ansible-lamp#2]
No ansible on vagrant box... can't provision. Getting the following error:

```
==> default: Running provisioner: ansible...
    default: Running ansible-playbook...
The Ansible software could not be found! Please verify
that Ansible is correctly installed on your host system.

If you haven't installed Ansible yet, please install Ansible
on your host system. Vagrant can't do this for you in a safe and
automated way.
Please check https://docs.ansible.com for more information.
```

**Comment by skecskes** [comment]
You are right, I just tried to `vagrant up` and have same error. I have new installed system without ansible. I had to install it to be able to run vagrant box. Try to run `ansible --version` in your terminal. If you don't see the version of installed ansible, then find instructions for your system and install ansible from here http://docs.ansible.com/ansible/intro_installation.html

Thanks for pointing this out. I will update the requirements.

**Comment by TimOgilvy** [comment]
Thanks. Also figured this out - forgot ansible runs on the local machine instead of the vagrant box. 

I'm on OS X Yosemite at the moment. Getting PIP and then Ansible was a fiddle.  I found this link particularly helpful http://binarynature.blogspot.com.au/2016/01/install-ansible-on-os-x-el-capitan_30.html 

Thanks again
